qcacmn: Fix build error when Green AP disabled
When the Green AP feature is disabled in the Kbuild the following
build issue is observed:

target_if_green_ap.h:59:10: error: 'struct wlan_green_ap_egap_params'
declared inside parameter list [-Werror]
target_if_green_ap.h:59:10: error: its scope is only this Defenderinition
or declaration, which is probably not what you want [-Werror]

Fix this by including a forward reference for the struct.

Change-Id: Ia5d867c0ebde17dba0f20c1e97391197ae9dbb77
CRs-Fixed: 2216249